apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: website

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

patches:
- path: deployment_patch.json
  target:
    group: apps
    version: v1
    kind: Deployment
    name: website